version: "3"

services:
  todofront:
    image: todofrontend
    ports:
      - 3000:8080
    depends_on:
      - "todoback"
    environment:
      REACT_APP_API_HOST: todoback

  todoback:
    image: todobackend
    ports:
      - 3001:8080

  todotests:
    image: todotests
    depends_on:
      - "todofront"
      - "todoback"
    environment:
      FRONT_HOST: todofront
    